import "./globals.css";
import { Great_Vibes, Cabin, Adamina, Open_Sans } from "next/font/google";

const greatVibes = Great_Vibes({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-great-vibes-src",
});

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin-src",
});

const adamina = Adamina({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-adamina-src",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans-src",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${greatVibes.variable} ${cabin.variable} ${adamina.variable} ${openSans.variable} bg-background text-foreground min-h-dvh`}>
        {children}
      </body>
    </html>
  );
}
